
/*
 *    Copyright (c) 2019 Google LLC.
 *    Copyright (c) 2016-2018 Nest Labs, Inc.
 *    All rights reserved.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

/*
 *    THIS FILE IS GENERATED. DO NOT MODIFY.
 *
 *    SOURCE TEMPLATE: trait.cpp.h
 *    SOURCE PROTO: weave/trait/power/battery_power_source_capabilities_trait.proto
 *
 */
#ifndef _WEAVE_TRAIT_POWER__BATTERY_POWER_SOURCE_CAPABILITIES_TRAIT_H_
#define _WEAVE_TRAIT_POWER__BATTERY_POWER_SOURCE_CAPABILITIES_TRAIT_H_

#include <Weave/Profiles/data-management/DataManagement.h>
#include <Weave/Support/SerializationUtils.h>

#include <weave/trait/power/PowerSourceCapabilitiesTrait.h>


namespace Schema {
namespace Weave {
namespace Trait {
namespace Power {
namespace BatteryPowerSourceCapabilitiesTrait {

extern const nl::Weave::Profiles::DataManagement::TraitSchemaEngine TraitSchema;

enum {
      kWeaveProfileId = (0x0U << 16) | 0x1bU
};

//
// Properties
//

enum {
    kPropertyHandle_Root = 1,

    //---------------------------------------------------------------------------------------------------------------------------//
    //  Name                                IDL Type                            TLV Type           Optional?       Nullable?     //
    //---------------------------------------------------------------------------------------------------------------------------//

    //
    //  type                                weave.trait.power.PowerSourceCapabilitiesTrait.PowerSourceType int               NO              NO
    //
    kPropertyHandle_Type = 2,

    //
    //  description                         weave.common.StringRef               union             YES             YES
    //
    kPropertyHandle_Description = 3,

    //
    //  nominal_voltage                     float                                uint32            NO              NO
    //
    kPropertyHandle_NominalVoltage = 4,

    //
    //  maximum_current                     float                                uint32            YES             YES
    //
    kPropertyHandle_MaximumCurrent = 5,

    //
    //  current_type                        weave.trait.power.PowerSourceCapabilitiesTrait.PowerSourceCurrentType int               NO              NO
    //
    kPropertyHandle_CurrentType = 6,

    //
    //  order                               uint32                               uint32            NO              NO
    //
    kPropertyHandle_Order = 7,

    //
    //  removable                           bool                                 bool              NO              NO
    //
    kPropertyHandle_Removable = 8,

    //
    //  rechargeable                        bool                                 bool              NO              NO
    //
    kPropertyHandle_Rechargeable = 9,

    //
    //  capacity                            float                                uint32            YES             YES
    //
    kPropertyHandle_Capacity = 10,

    //
    //  chemistry                           BatteryChemistry                     int               NO              NO
    //
    kPropertyHandle_Chemistry = 11,

    //
    //  count                               uint32                               uint32            NO              NO
    //
    kPropertyHandle_Count = 12,

    //
    //  replaceable                         BatteryReplaceability                int               NO              NO
    //
    kPropertyHandle_Replaceable = 13,

    //
    //  designations                        BatteryDesignation                   structure         YES             YES
    //
    kPropertyHandle_Designations = 14,

    //
    //  designation_description             weave.common.StringRef               union             YES             YES
    //
    kPropertyHandle_Designations_DesignationDescription = 15,

    //
    //  common_designation_identifier       CommonBatteryDesignationIdentifier   int               YES             NO
    //
    kPropertyHandle_Designations_CommonDesignationIdentifier = 16,

    //
    //  ansi_designation_identifier         ANSIBatteryDesignationIdentifier     int               YES             NO
    //
    kPropertyHandle_Designations_AnsiDesignationIdentifier = 17,

    //
    //  iec_designation_identifier          IECBatteryDesignationIdentifier      int               YES             NO
    //
    kPropertyHandle_Designations_IecDesignationIdentifier = 18,

    //
    // Enum for last handle
    //
    kLastSchemaHandle = 18,
};

//
// Event Structs
//

struct BatteryDesignation
{
    const char * designationDescription;
    void SetDesignationDescriptionNull(void);
    void SetDesignationDescriptionPresent(void);
#if WEAVE_CONFIG_SERIALIZATION_ENABLE_DESERIALIZATION
    bool IsDesignationDescriptionPresent(void);
#endif
    int32_t commonDesignationIdentifier;
    int32_t ansiDesignationIdentifier;
    int32_t iecDesignationIdentifier;
    uint8_t __nullified_fields__[1/8 + 1];

    static const nl::SchemaFieldDescriptor FieldSchema;

};

struct BatteryDesignation_array {
    uint32_t num;
    BatteryDesignation *buf;
};

inline void BatteryDesignation::SetDesignationDescriptionNull(void)
{
    SET_FIELD_NULLIFIED_BIT(__nullified_fields__, 0);
}

inline void BatteryDesignation::SetDesignationDescriptionPresent(void)
{
    CLEAR_FIELD_NULLIFIED_BIT(__nullified_fields__, 0);
}

#if WEAVE_CONFIG_SERIALIZATION_ENABLE_DESERIALIZATION
inline bool BatteryDesignation::IsDesignationDescriptionPresent(void)
{
    return (!GET_FIELD_NULLIFIED_BIT(__nullified_fields__, 0));
}
#endif
//
// Enums
//

enum BatteryChemistry {
    BATTERY_CHEMISTRY_ALKALINE = 1,
    BATTERY_CHEMISTRY_LITHIUM_CARBON_FLUORIDE = 2,
    BATTERY_CHEMISTRY_LITHIUM_CHROMIUM_OXIDE = 3,
    BATTERY_CHEMISTRY_LITHIUM_COPPER_OXIDE = 4,
    BATTERY_CHEMISTRY_LITHIUM_IRON_DISULFIDE = 5,
    BATTERY_CHEMISTRY_LITHIUM_MANGANESE_DIOXIDE = 6,
    BATTERY_CHEMISTRY_LITHIUM_THIONYL_CHLORIDE = 7,
    BATTERY_CHEMISTRY_MAGNESIUM = 8,
    BATTERY_CHEMISTRY_MERCURY_OXIDE = 9,
    BATTERY_CHEMISTRY_NICKEL_OXYHYDRIDE = 10,
    BATTERY_CHEMISTRY_SILVER_OXIDE = 11,
    BATTERY_CHEMISTRY_ZINC_AIR = 12,
    BATTERY_CHEMISTRY_ZINC_CARBON = 13,
    BATTERY_CHEMISTRY_ZINC_CHLORIDE = 14,
    BATTERY_CHEMISTRY_LEAD_ACID = 32,
    BATTERY_CHEMISTRY_LITHIUM_COBALT_OXIDE = 33,
    BATTERY_CHEMISTRY_LITHIUM_ION = 34,
    BATTERY_CHEMISTRY_LITHIUM_ION_POLYMER = 35,
    BATTERY_CHEMISTRY_LITHIUM_IRON_PHOSPHATE = 36,
    BATTERY_CHEMISTRY_LITHIUM_SULFUR = 37,
    BATTERY_CHEMISTRY_LITHIUM_TITANATE = 38,
    BATTERY_CHEMISTRY_NICKEL_CADMIUM = 39,
    BATTERY_CHEMISTRY_NICKEL_HYDROGEN = 40,
    BATTERY_CHEMISTRY_NICKEL_IRON = 41,
    BATTERY_CHEMISTRY_NICKEL_METAL_HYDRIDE = 42,
    BATTERY_CHEMISTRY_NICKEL_ZINC = 43,
    BATTERY_CHEMISTRY_SILVER_ZINC = 44,
    BATTERY_CHEMISTRY_SODIUM_ION = 45,
    BATTERY_CHEMISTRY_SODIUM_SULFUR = 46,
    BATTERY_CHEMISTRY_ZINC_BROMIDE = 47,
    BATTERY_CHEMISTRY_ZINC_CERIUM = 48,
};

enum BatteryReplaceability {
    BATTERY_REPLACEABILITY_NOT_REPLACEABLE = 1,
    BATTERY_REPLACEABILITY_USER_REPLACEABLE = 2,
    BATTERY_REPLACEABILITY_FACTORY_REPLACEABLE = 3,
};

enum CommonBatteryDesignationIdentifier {
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_AAA = 1,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_AA = 2,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_C = 3,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_D = 4,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_4V5 = 5,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_6V0 = 6,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_9V0 = 7,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_1_2AA = 8,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_AAAA = 9,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_A = 10,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_B = 11,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_F = 12,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_N = 13,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_NO6 = 14,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_SUBC = 15,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_A23 = 16,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_A27 = 17,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_BA5800 = 18,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_DUPLEX = 19,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_4SR44 = 20,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_523 = 21,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_531 = 22,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_15V0 = 23,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_22V5 = 24,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_30V0 = 25,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_45V0 = 26,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_67V5 = 27,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_J = 28,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_CR123A = 29,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_CR2 = 30,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_2CR5 = 31,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_CR_P2 = 32,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_CR_V3 = 33,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_SR41 = 34,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_SR43 = 35,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_SR44 = 36,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_SR45 = 37,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_SR48 = 38,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_SR54 = 39,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_SR55 = 40,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_SR57 = 41,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_SR58 = 42,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_SR59 = 43,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_SR60 = 44,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_SR63 = 45,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_SR64 = 46,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_SR65 = 47,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_SR66 = 48,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_SR67 = 49,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_SR68 = 50,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_SR69 = 51,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_SR516 = 52,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_SR731 = 53,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_SR712 = 54,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_LR932 = 55,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_A5 = 56,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_A10 = 57,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_A13 = 58,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_A312 = 59,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_A675 = 61,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_AC41E = 62,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_10180 = 63,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_10280 = 64,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_10440 = 65,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_14250 = 66,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_14430 = 67,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_14500 = 68,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_14650 = 69,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_15270 = 70,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_16340 = 71,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_RCR123A = 72,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_17500 = 73,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_17670 = 74,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_18350 = 75,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_18500 = 76,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_18650 = 77,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_19670 = 78,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_25500 = 79,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_26650 = 80,
    COMMON_BATTERY_DESIGNATION_IDENTIFIER_32600 = 81,
};

enum ANSIBatteryDesignationIdentifier {
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_24A = 1,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_24D = 2,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_24LF = 3,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_15A = 4,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_15D = 5,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_15LF = 6,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_1P2H2 = 7,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_1P2K2 = 8,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_14A = 9,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_14D = 10,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_13A = 11,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_13D = 12,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_3LR12 = 13,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_3R12 = 14,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_1604A = 15,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_1604D = 16,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_1604LC = 17,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_7P2H5 = 18,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_11604 = 19,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_908A = 20,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_908D = 21,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_25A = 22,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_60 = 23,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_910A = 24,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_910D = 25,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_905 = 26,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_1811A = 27,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_1306A = 28,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_1307AP = 29,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_220 = 30,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_215 = 31,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_210 = 32,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_213 = 33,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_217 = 34,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_1412A = 35,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_915 = 36,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_915A = 37,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_918A = 38,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_5018LC = 39,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_5046LC = 40,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_5032LC = 41,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_5024LC = 42,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_5047LC = 43,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_5047LF = 44,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_5033LC = 45,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_5034LC = 46,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_5012LC = 47,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_5020LC = 48,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_5009LC = 49,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_5000LC = 50,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_5003LC = 51,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_5004LC = 52,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_5011LC = 53,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_5029LC = 54,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_1135SO = 55,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_1134SO = 56,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_1133SO = 57,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_1132SO = 58,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_1166A = 59,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_1107SO = 61,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_1131SOP = 62,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_1136SO = 63,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_1138SO = 64,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_1160SO = 65,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_1165SO = 66,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_1158SO = 67,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_1163SO = 68,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_1175SO = 69,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_1176SO = 70,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_7012ZD = 71,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_7005ZD = 72,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_7000ZD = 73,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_7002ZD = 74,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_7003ZD = 75,
    ANSI_BATTERY_DESIGNATION_IDENTIFIER_7001Z = 76,
};

enum IECBatteryDesignationIdentifier {
    IEC_BATTERY_DESIGNATION_IDENTIFIER_LR03 = 1,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_R03 = 2,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_FR03 = 3,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_HR03 = 4,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_KR03 = 5,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_ZR03 = 6,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_LR6 = 7,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_R6 = 8,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_FR6 = 9,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_HR6 = 10,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_KR6 = 11,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_ZR6 = 12,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_LR14 = 13,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_R14 = 14,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_HR14 = 15,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_KR14 = 16,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_ZR14 = 17,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_LR20 = 18,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_R20 = 19,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_HR20 = 20,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_KR20 = 21,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_ZR20 = 22,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_3LR12 = 23,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_3R12 = 24,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_6LR61 = 25,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_6F22 = 26,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_6KR61 = 27,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_6HR61 = 28,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_4LR25Y = 29,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_4R25 = 30,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_CR14250 = 31,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_ER14250 = 32,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_LR8D425 = 33,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_R23 = 34,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_LR23 = 35,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_R12 = 36,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_LR12 = 37,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_R25 = 38,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_LR25 = 39,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_LR1 = 40,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_R1 = 41,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_HR1 = 42,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_KR1 = 43,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_R40 = 44,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_KR22C429 = 45,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_HR22C429 = 46,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_8LR932 = 47,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_8LR732 = 48,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_2R10 = 49,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_4LR44 = 50,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_3LR50 = 51,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_10F15 = 52,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_15F20 = 53,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_20F20 = 54,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_30F20 = 55,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_4LR61 = 56,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_4R25X = 57,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_4LR25X = 58,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_4R25_2 = 59,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_4LR25_2 = 61,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_CR17345 = 62,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_CR15H270 = 63,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_2CR5 = 64,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_CR_P2 = 65,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_CR927 = 66,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_CR1025 = 67,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_CR1130 = 68,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_CR1216 = 69,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_CR1220 = 70,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_CR1225 = 71,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_CR1616 = 72,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_CR1620 = 73,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_CR1632 = 74,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_CR2012 = 75,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_CR2016 = 76,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_CR2020 = 77,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_CR2025 = 78,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_CR2032 = 79,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_CR2320 = 80,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_CR2325 = 81,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_CR2330 = 82,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_CR2354 = 83,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_CR2412 = 84,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_CR2430 = 85,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_CR2450 = 86,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_CR2477 = 87,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_CR3032 = 88,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_CR11108 = 89,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_LR736 = 90,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_SR736 = 91,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_LR1142 = 92,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_SR1142 = 93,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_LR1154 = 94,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_SR1154 = 95,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_LR936 = 96,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_SR936 = 97,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_LR754 = 98,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_SR754 = 99,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_LR1131 = 100,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_SR1131 = 101,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_LR1121 = 102,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_SR1121 = 103,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_SR1116SW = 104,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_LR926 = 105,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_SR926 = 106,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_LR721 = 107,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_SR721 = 108,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_LR726 = 109,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_SR726 = 110,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_LR621 = 111,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_SR621 = 112,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_LR521 = 113,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_SR521 = 114,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_LR527 = 115,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_SR527 = 116,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_LR65 = 117,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_LR626 = 118,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_SR626 = 119,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_SR716 = 120,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_LR916 = 121,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_SR916 = 122,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_LR921 = 123,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_SR921 = 124,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_LR516 = 125,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_SR516 = 126,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_LR416 = 127,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_SR416 = 128,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_LR731 = 129,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_SR731 = 130,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_SR712 = 131,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_LR932 = 132,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_PR63 = 133,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_PR70 = 134,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_PR48 = 135,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_PR41 = 136,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_PR44 = 137,
    IEC_BATTERY_DESIGNATION_IDENTIFIER_PR43 = 138,
};

} // namespace BatteryPowerSourceCapabilitiesTrait
} // namespace Power
} // namespace Trait
} // namespace Weave
} // namespace Schema
#endif // _WEAVE_TRAIT_POWER__BATTERY_POWER_SOURCE_CAPABILITIES_TRAIT_H_
